### ISSUE TITLE
Change menu on homepage to SVG w/ animation

### ISSUE THREAD

**Issue by evmoriarty** [SrgSprinkles/portfolio#11]

**Comment by evmoriarty** [comment]
For the time being, I made the menu on the same side as the blog in [commit f40e0da2909325c67def3949f4330d0daacafc41](https://github.com/SrgSprinkles/portfolio/commit/f40e0da2909325c67def3949f4330d0daacafc41).

**Comment by SrgSprinkles** [comment]
For the time being, I made the menu on the same side as the blog in [commit f40e0da2909325c67def3949f4330d0daacafc41](https://github.com/SrgSprinkles/portfolio/commit/f40e0da2909325c67def3949f4330d0daacafc41).
